<?php
/**
 * Studioforty9_Recaptcha
 *
 * @category  Studioforty9
 * @package   Studioforty9_Recaptcha
 * @author    StudioForty9 <info@studioforty9.com>
 * @copyright 2015 StudioForty9 (http://www.studioforty9.com)
 * @license   https://github.com/studioforty9/recaptcha/blob/master/LICENCE BSD
 * @version   1.5.7
 * @link      https://github.com/studioforty9/recaptcha
 * @see       Studioforty9_Recaptcha_Block_Explicit
 */

/** @var $this Studioforty9_Recaptcha_Block_Explicit */
$id = $this->getRecaptchaId();

$formHandle = $this->getFormHandle() ? $this->getFormHandle() : 'dataForm';
$buttonSelector = $this->getButtonSelector() ? $this->getButtonSelector() : 'button[type=submit]';

?>
<?php if ($this->isAllowed($this->getAction()->getFullActionName())): ?>
    <?php if ($this->getRecaptchaType() == 'invisible'): ?>
        <ul class="messages" id="recaptcha-messages-<?php echo $id ?>" style="display: none">
            <li class="error-msg"><ul><li></li></ul></li>
        </ul>
        <div class="recaptcha" id="recaptcha-<?php echo $id ?>">
            <script type="text/javascript">
                if (typeof recaptchaRenderCallbacks === 'undefined') {
                    var recaptchaRenderCallbacks = [];
                }
                recaptchaRenderCallbacks.push(function () {
                    var button = jQuery('#recaptcha-<?php echo $id ?>').closest('form').find('<?php echo $buttonSelector ?>')[0];
                    jQuery(button).on('click',function(event, isLoaded){
                        if (isLoaded == 'loaded') {
                            return true;
                        }
                        var widgetId = grecaptcha.render(button, {
                            'sitekey': "<?php echo $this->getSiteKey(); ?>",
                            'theme': "<?php echo $this->getTheme(); ?>",
                            'type': "<?php echo $this->getType(); ?>",
                            'size': "invisible",
                            'badge': "<?php echo $this->getBadgeLocation(); ?>",
                            'error-callback': function() {
                                recaptchaShowErrorAndRetry('<?php echo $id ?>', widgetId);
                            },
                            'callback': function(response) {
                                var form = <?php echo $formHandle ?>;
                                if (form.validator && form.validator.validate()){
                                    console.log('reCaptcha ('+widgetId+') passsed and form is valid');
                                    form.submit();
                                } else {
                                    console.log('reCaptcha ('+widgetId+') passsed but form not valid, resetting');
                                    grecaptcha.reset(widgetId);
                                }
                            }
                        });

                        jQuery(button).trigger('click', ['loaded']);
                        return false;
                    });
                });
            </script>
        </div>
    <?php else: ?>
        <div class="recaptcha" style="overflow:hidden;position:relative;margin-bottom:10px;">
            <input type="checkbox" id="cb-<?php echo $id ?>" name="cb-<?php echo $id ?>" value="" class="required-entry" style="visibility:hidden; position:absolute; left:-1000000px" />
            <div id="el-<?php echo $id ?>"></div>
            <script type="text/javascript">
                if (typeof recaptchaRenderCallbacks === 'undefined') {
                    var recaptchaRenderCallbacks = [];
                }
                recaptchaRenderCallbacks.push(function () {
                    grecaptcha.render('el-<?php echo $id ?>', {
                        'sitekey': "<?php echo $this->getSiteKey(); ?>",
                        'theme': "<?php echo $this->getTheme(); ?>",
                        'type': "<?php echo $this->getType(); ?>",
                        'size': "<?php echo $this->getSize(); ?>",
                        'callback': function(response) {
                            if (response.length > 0) {
                                $('cb-<?php echo $id ?>').writeAttribute('value', 'checked');
                                $('cb-<?php echo $id ?>').checked = true;
                            }
                        }
                    });
                });
            </script>
        </div>
    <?php endif; ?>
<?php endif; ?>
